services:
  netbox:
    image: netbox:plugins
    pull_policy: never
    build:
      context: .
      dockerfile: Dockerfile-Plugins
      args:
        VERSION: latest
    environment:
      SKIP_SUPERUSER: "true"
  netbox-worker:
    image: netbox:plugins
    pull_policy: never
  netbox-housekeeping:
    image: netbox:plugins
    pull_policy: never
  tls:
    image: caddy:2-alpine
    restart: always
    depends_on:
      - netbox
    volumes:
      - ./server.crt:/etc/ssl/private/server.crt:ro,z
      - ./server.key:/etc/ssl/private/server.key:ro,z
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - 443:443
